# BEGIN programs/mock_cp_amm/Cargo.toml
[package]
name    = "mock_cp_amm"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29.0"

[lib]
crate-type = ["cdylib", "lib"]
# END programs/mock_cp_amm/Cargo.toml
